### ISSUE TITLE
A bug about piece generation

### ISSUE THREAD

**Issue by C-Albert-hub** [jjinux/gotetris#12]
* The function getPiece in model.go file, that only generate one type piece.
* After my tries, I understand you didn't use dxBank and dyBank.
* So, I help you modify your problem.
### This is the code to be modified:
```
func (g *Game) getPiece() bool {
	g.piece = 1 + rand.Int()%numTypes
	g.x = boardWidth / 2 //come the middle of board
	g.y = 0

	g.dx = dxBank[g.piece]
	g.dy = dyBank[g.piece]

	for k := 0; k < numSquares; k++ {
		g.dxPrime[k] = g.dx[k]
		g.dyPrime[k] = g.dy[k]
	}
	if !g.pieceFits(g.x, g.y) {
		return false
	}
	return true
}
```

**Comment by jjinux** [comment]
I don't understand what you're trying to say. As far as I can tell, the game is working fine. Feel free to send a PR.
