### ISSUE TITLE
win7 go version go1.4.2 windows/386

### ISSUE THREAD

**Issue by axgle** [jjinux/gotetris#3]
![gotetris](https://cloud.githubusercontent.com/assets/21093/7831502/df68f548-0489-11e5-8038-c4b866331bde.png)

**Comment by jjinux** [comment]
Hey, @axgle, thanks for the bug report! Do you want to help debug this? I don't actually have a Windows machine. I wonder if it's a bug in the termbox-go library's support for Windows.

**Comment by jjinux** [comment]
Hey, @axgle, thanks for the bug report! Do you want to help debug this? I don't actually have a Windows machine. I wonder if it's a bug in the termbox-go library's support for Windows.

**Comment by axgle** [comment]
when remove `\u2190` etc chars,it's seem that ok

**Comment by jjinux** [comment]
I pushed a version that doesn't use those unicode characters. Can you try it out? If it works, go ahead and close the bug. Thanks!

**Comment by axgle** [comment]
It's OK now

**Comment by jjinux** [comment]
Thanks!
